### ISSUE TITLE
Deep last modified time query for scss fails due to attempt to compile partial assets

### ISSUE THREAD

**Issue by tamcy** [symfony/AsseticBundle#322]
* I doubt if it matters, but anyway I am working on Windows machine and attempting to compile the scss version of Twitter Bootstrap 3.
 * It doesn't affect assetic:dump. Only the dev environment is affected when assets are requested and intercepted by AsseticController.

The dev css compilation fails when updated to the latest assetic bundle. Tried some digging and it turns out that the cause is on line 72 of `AsseticController.php`. It looks like that the logic is to try to extract the included files and query their last modified time in order to see if there is a need for re-compilation. 

However there is a problem. SccsPhpFilter tries to compile those included (partial) files, which doesn't work because those files are not meant to be compiled individually. For bootstrap 3, the controller throws a 500 internal server error because of the mixins are undefined in _scaffolding.scss.

**Comment by stof** [comment]
if the ScssPhpFilter implementation is broken, an issue (or even a PR) should be opened on Assetic itself.

**Comment by alex88** [comment]
@tamcy have you found anything else? Opened an issue in Assetic? I've the issue with bootstrap partial files that are compiled and so missing any reference to other mixins just with `assetic:watch`

**Comment by alex88** [comment]
FWIW I've opened this issue https://github.com/kriswallsmith/assetic/issues/785

**Comment by tamcy** [comment]
@alex88 I actually forgot about this issue already. I ended up not using assetic to build the bootstrap css.
