### ISSUE TITLE
console assetic:dump triggers authentication check

### ISSUE THREAD

**Issue by dspiegel** [symfony/AsseticBundle#365]
Currently In process of moving from 2.3 LTS to 2.7 LTS and have found strange issue running **console assetic:dump** command. Not sure if I have to set flag in my auth service somehow to ignore it if using console.

Thanks, Dave

**Background**:
I have been using my own AuthFactory/Provide in 2.3, but now decided to use new authenticator provider and simple-preauth firewall. I removed my previous custom Factory/Provider.  To authenticate, a var is passed via http header which is then used to query database for user info. That all works as expected.

**Issue**: 
I found with both my previous and new Authentication, that running **console assetic:dump** command, the authentication is ran and fails, so the dump fails as well. I don't understand why the authentication should be ran when running any console command. Not sure if this is my cause or something in 2.6/2.7 (happened in both versions).

**Stack Trace**:
 Dst\AuthBundle\Security\DstAuthUserProvider->__construct() at /export/home/dave/Projects/iprd/auth-bundle/Security/DstAuthAuthenticator.php:29

 Dst\AuthBundle\Security\DstAuthAuthenticator->__construct() at /export/home/dave/Projects/iprd/myon2/app/cache/dev/appDevDebugProjectContainer.php:923

 appDevDebugProjectContainer->getDstAuthAuthenticatorService() at /export/home/dave/Projects/iprd/myon2/app/bootstrap.php.cache:2140

 Symfony\Component\DependencyInjection\Container->get() at /export/home/dave/Projects/iprd/myon2/app/cache/dev/appDevDebugProjectContainer.php:3772

 appDevDebugProjectContainer->getSecurity_Authentication_ManagerService() at /export/home/dave/Projects/iprd/myon2/app/bootstrap.php.cache:2140

 Symfony\Component\DependencyInjection\Container->get() at /export/home/dave/Projects/iprd/myon2/app/cache/dev/appDevDebugProjectContainer.php:2279

 appDevDebugProjectContainer->getSecurity_AuthorizationCheckerService() at /export/home/dave/Projects/iprd/myon2/app/bootstrap.php.cache:2140

 Symfony\Component\DependencyInjection\Container->get() at /export/home/dave/Projects/iprd/myon2/app/cache/dev/appDevDebugProjectContainer.php:3388

 appDevDebugProjectContainer->getTwigService() at /export/home/dave/Projects/iprd/myon2/app/bootstrap.php.cache:2140

 Symfony\Component\DependencyInjection\Container->get() at /export/home/dave/Projects/iprd/myon2/app/cache/dev/appDevDebugProjectContainer.php:329

 appDevDebugProjectContainer->getAssetic_AssetManagerService() at /export/home/dave/Projects/iprd/myon2/app/bootstrap.php.cache:2140

 Symfony\Component\DependencyInjection\Container->get() at /export/home/dave/Projects/iprd/myon2/vendor/symfony/assetic-bundle/Command/AbstractCommand.php:28

 Symfony\Bundle\AsseticBundle\Command\AbstractCommand->initialize() at /export/home/dave/Projects/iprd/myon2/vendor/symfony/assetic-bundle/Command/DumpCommand.php:63

 Symfony\Bundle\AsseticBundle\Command\DumpCommand->initialize() at /export/home/dave/Projects/iprd/myon2/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:238

 Symfony\Component\Console\Command\Command->run() at /export/home/dave/Projects/iprd/myon2/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886

 Symfony\Component\Console\Application->doRunCommand() at /export/home/dave/Projects/iprd/myon2/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195

 Symfony\Component\Console\Application->doRun() at /export/home/dave/Projects/iprd/myon2/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96

 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /export/home/dave/Projects/iprd/myon2/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126

 Symfony\Component\Console\Application->run() at /export/home/dave/Projects/iprd/myon2/app/console:22

**Installed Packages**:
* doctrine/annotations           v1.2.4           Docblock Annotations Parser
* doctrine/cache                 v1.4.1           Caching library offering an object-oriented API for many cache backends
* doctrine/collections           v1.3.0           Collections Abstraction library
* doctrine/common                v2.5.0           Common Library for Doctrine projects
* doctrine/dbal                  v2.4.4           Database Abstraction Layer
* doctrine/doctrine-bundle       v1.5.0           Symfony DoctrineBundle
* doctrine/doctrine-cache-bundle v1.0.1           Symfony2 Bundle for Doctrine Cache
* doctrine/inflector             v1.0.1           Common String Manipulations with regard to casing and singular/plural rules.
* doctrine/lexer                 v1.0.1           Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
* doctrine/orm                   v2.4.7           Object-Relational-Mapper for PHP
* jdorn/sql-formatter            v1.2.17          a PHP SQL highlighting library
* jms/aop-bundle                 1.0.1            Adds AOP capabilities to Symfony2
* jms/cg                         1.0.0            Toolset for generating PHP code
* jms/di-extra-bundle            1.5.0            Allows to configure dependency injection using annotations
* jms/metadata                   1.5.1            Class/method/property metadata management in PHP
* jms/parser-lib                 1.0.0            A library for easily creating recursive-descent parsers.
* jms/security-extra-bundle      1.5.1            Enhances the Symfony2 Security Component by adding several new features
* knplabs/knp-menu               v1.1.2           An object oriented menu library
* knplabs/knp-menu-bundle        v1.1.2           This bundle provides an integration of the KnpMenu library
* kriswallsmith/assetic          v1.2.1           Asset Management for PHP
* monolog/monolog                1.13.1           Sends your logs to files, sockets, inboxes, databases and various web services
* phing/phing                    2.11.0           PHing Is Not GNU make; it's a PHP project build system or build tool based on A...
* phpoption/phpoption            1.4.0            Option Type for PHP
* psr/log                        1.0.0            Common interface for logging libraries
* sensio/distribution-bundle     v3.0.29          Base bundle for Symfony Distributions
* sensio/framework-extra-bundle  v3.0.9           This bundle provides a way to configure your controllers with annotations
* sensio/generator-bundle        v2.5.3           This bundle generates code for you
* sensiolabs/security-checker    v2.0.5           A security checker for your composer.lock
* swiftmailer/swiftmailer        v5.4.0           Swiftmailer, free feature-rich PHP mailer
* symfony/assetic-bundle         v2.6.1           Integrates Assetic into Symfony2
* symfony/monolog-bundle         v2.7.1           Symfony MonologBundle
* symfony/swiftmailer-bundle     v2.3.8           Symfony SwiftmailerBundle
* symfony/symfony                v2.7.0           The Symfony PHP framework
* twig/twig                      v1.18.1          Twig, the flexible, fast, and secure template language for PHP

**Comment by stof** [comment]
The authentication is not triggered at all. Assetic is simply instantiating Twig, which depends on the security system (because of the ``is_granted`` Twig function). This means it is instantiating your provider. but it does not call it.
If you are making DB calls in the constructor, the issue is in your own service: putting logic in the constructor makes your class totally unfriendly to dependency injection (and Symfony uses DI everywhere)
