### ISSUE TITLE
scoped service assetic.helper.static triggers deprecation notice with Symfony 2.8

### ISSUE THREAD

**Issue by craue** [symfony/AsseticBundle#372]
When using this bundle in a project with Symfony 2.8, the service `assetic.helper.static` triggers a deprecation notice because of its scope:

`The "scope" attribute of service "assetic.helper.static" in file ".../vendor/symfony/assetic-bundle/DependencyInjection/../Resources/config/templating_php.xml" is deprecated since version 2.8 and will be removed in 3.0.`

I've noticed this when [testing my bundle with Symfony 2.8](https://github.com/craue/CraueConfigBundle/pull/22).

**Comment by craue** [comment]
The referenced PR fixed the issue.

**Comment by mephir** [comment]
and throw error 
```
Scope Widening Injection detected: The definition "assetic.helper.static" references the service "templating.helper.assets" which belongs to a narrower scope.
```
while using sf < 2.8

**Comment by stof** [comment]
@mephir please open a dedicated issue for your problem instead of commenting on an unrelated closed issue (and please give a bit more details)
