### ISSUE TITLE
Compile Error due to an interface change

### ISSUE THREAD

**Issue by jdgriffith** [symfony/AsseticBundle#376]
```
Compile Error: Declaration of Symfony\Bundle\AsseticBundle\Twig\AsseticNodeVisitor::enterNode() must be compatible with Twig_NodeVisitorInterface::ent  
  erNode(Twig_Node $node, Twig_Environment $env)
```

This is happening in my environment. I am running Symfony 2.7.* and assetic-bundle ^2.6@dev. 

This is happening because the first parameter of enterNode and leaveNode of  Twig_NodeInterface needs to be changed to just Twig_Node. 

```
    public function enterNode(\Twig_NodeInterface $node, \Twig_Environment $env)
    {
        return $node;
    }

    public function leaveNode(\Twig_NodeInterface $node, \Twig_Environment $env)
```

Is there a fix or workaround for this already? Please let me know as my environment is foobar'd due to this.

**Comment by stof** [comment]
This is because this bundle is not yet compatible with Twig 2 (this is in progress in #375) and Symfony 2.7 now allows both Twig 1.x and Twig 2.
there is several ways to fix this:

- add an requirement on ``twig/twig: 1.*`` in your composer.json to force using Twig 1
- don't allow dev versions of all packages (Twig 2 is not released)

**Comment by stof** [comment]
btw, this bundle might not be the only one incompatible with Twig 2. I suggest you to stick to Twig 1 in your projects for now.

**Comment by jdgriffith** [comment]
Ok thanks for the quick reply. I assumed this was something being worked on or was known about. I will enforce my application to use 1.*. 

Thanks!

**Comment by EdwardIII** [comment]
Polite ping - I think twig 2.0 is now final: https://github.com/twigphp/Twig/releases  Is this still on the radar?

**Comment by stof** [comment]
``JMS\TranslationBundle\Twig\NormalizingNodeVisitor`` has **strictly** nothing to do with AsseticBundle. Please read error messages you get before reproting them to a project.

**Comment by EdwardIII** [comment]
Sorry about that - bad mistake. Deleting original message and this one too
